services:
  - type: web
    name: twitter-backend
    env: node
    plan: free
    buildCommand: |
      npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: twitter-frontend
    env: static
    buildCommand: |
      cd frontend
      rm -rf node_modules package-lock.json
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        fromService:
          name: twitter-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
